#48 Angular10 Update
systelab/systelab-charts pull request #49
Opened 2020-11-05 12:56 UTC by VictorDeBlas

2020-11-06 10:59 UTC, alfonsserra approved these changes

2020-11-06 14:42 UTC, vinyulis requested changes

2020-11-06 14:42 UTC, vinyulis commented on projects/systelab-charts/package.json
>      "@angular/common": ">=9.0.0 <10.0.0",
Why these dependencies are not changed? Should be >=10 <11?

2020-11-06 14:42 UTC, vinyulis commented on projects/systelab-charts/package.json
>      "url": "https://github.com/systelab/systelab-charts.git"
Could we increase the major version of this package.json?

2020-11-09 13:29 UTC, VictorDeBlas commented on projects/systelab-charts/package.json
>      "url": "https://github.com/systelab/systelab-charts.git"
Done

2020-11-09 23:23 UTC, vinyulis approved these changes
OK!!. Thanks!!.

2020-11-19 14:06 UTC, carlosra85 approved these changes

2020-11-19 15:22 UTC, merged